Projekt-Dateien in .tools/project geschoben (#6386)
Da diese nicht mehr zum Core-Repo gehören werden, aber für Testzwecke weiter benötigt werden

diff --git a/.github/workflows/styles-compile.yml b/.github/workflows/styles-compile.yml
--- a/.github/workflows/styles-compile.yml
+++ b/.github/workflows/styles-compile.yml
@@ -66,12 +66,12 @@ jobs:
                 run: |
                     sudo /etc/init.d/mysql start
                     mysql -uroot -h127.0.0.1 -proot -e 'create database redaxo6;'
-                    php redaxo/bin/console setup:run -n --lang=de_de --db-host=127.0.0.1 --db-name=redaxo6 --db-password=root --db-createdb=no --db-setup=normal --admin-username=admin --admin-password=adminpassword --error-email=test@redaxo.invalid --ansi -v
-                    php redaxo/bin/console config:set --type boolean debug.enabled true -v
-                    php redaxo/bin/console config:set --type boolean debug.throw_always_exception true -v
+                    php .tools/bin/console setup:run -n --lang=de_de --db-host=127.0.0.1 --db-name=redaxo6 --db-password=root --db-createdb=no --db-setup=normal --admin-username=admin --admin-password=adminpassword --error-email=test@redaxo.invalid --ansi -v
+                    php .tools/bin/console config:set --type boolean debug.enabled true -v
+                    php .tools/bin/console config:set --type boolean debug.throw_always_exception true -v
 
             -   name: Compile styles
-                run: php redaxo/bin/console assets:compile-styles --ansi -v
+                run: php .tools/bin/console assets:compile-styles --ansi -v
 
             -   name: Commit changed files
                 uses: stefanzweifel/git-auto-commit-action@v7
@@ -87,4 +87,4 @@ jobs:
                 if: env.writable == 0
                 run: |
                     # check if compiling the scss lead to uncommitted changes
-                    git diff HEAD --exit-code --output=/dev/null || (echo "::error::It seems you missed to commit the compiled css files, run 'redaxo/bin/console assets:compile-styles' and push the changes." && exit 1)
+                    git diff HEAD --exit-code --output=/dev/null || (echo "::error::It seems you missed to commit the compiled css files, run '.tools/bin/console assets:compile-styles' and push the changes." && exit 1)
